version: '3.0'
services:
  postgres_new:
    image: postgres:latest
    container_name: postgres_container_new
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=am_db_dev
    volumes:
      - postgres-db-volume_dev_new:/var/lib/postgresql/data
    networks:
      - postgres-db-network-new

  mongodb_new:
    image: mongodb/mongodb-community-server:7.0.3-ubuntu2204-20240323T084243Z
    container_name: mongodb_new
    restart: always
    ports:
      - "27022:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: candidate_new
    volumes:
      - mongodb_data_new:/docker/mongodb/data
    networks:
      - mongodb-network-new

  academic_mback:
    image: academic-mg-back:0.0.1
    container_name: academic-mg-back
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres_new
      - mongodb_new
    ports:
      - 8080:8080
    networks:
      - postgres-db-network-new
volumes:
  postgres-db-volume_dev_new:
    driver: local
  mongodb_data_new:
    driver: local
networks:
  postgres-db-network-new:
    driver: bridge
  mongodb-network-new:
    driver: bridge