-- Insertar materias para la Facultad de Ciencias Económicas
INSERT INTO subject (id, "name", initials, active, area_id)
VALUES
    (1, 'ADMINISTRACION GENERAL', 'AG', true, 1),
    (2, 'ALGEBRA', 'AL', true, 1),
    (3, 'CONTABILIDAD I', 'CI', true, 1),
    (4, 'DERECHO COMERCIAL', 'DC', true, 1),
    (5, 'MATEMATICA FINANCIERA', 'MF', true, 1),
    (6, 'CALCULO', 'CA', true, 1),
    (7, 'CONTABILIDAD II', 'CII', true, 1),
    (8, 'DERECHO DEL TRABAJO', 'DT', true, 1),
    (9, 'ECONOMIA GENERAL', 'EG', true, 1),
    (10, 'SISTEMAS ADMINISTRATIVOS', 'SA', true, 1),
    (11, 'SEMINARIO BASICO', 'SB', true, 1),
    (12, 'CONTABILIDAD III', 'CIII', true, 1),
    (13, 'MICROECONOMIA', 'MI', true, 1),
    (14, 'ESTADISTICA I', 'EI', true, 1),
    (15, 'INVESTIGACION OPERATIVA', 'IO', true, 1),
    (16, 'MACROECONOMIA', 'MA', true, 1),
    (17, 'CONTABILIDAD DE BANCOS Y ENTIDADES FINANCIERAS', 'CB', true, 1),
    (18, 'ESTADISTICA II', 'EII', true, 1),
    (19, 'ADM. DE PERSONAL', 'AP', true, 1),
    (20, 'COSTOS I', 'COI', true, 1),
    (21, 'INFORMATICA I', 'II', true, 1),
    (22, 'GESTION DE RIESGOS', 'GR', true, 1),
    (23, 'DERECHO TRIBUTARIO', 'DTT', true, 1),
    (24, 'CONTABILIDAD PETROLERA Y MINERA', 'CPM', true, 1),
    (25, 'COSTOS II', 'COII', true, 1),
    (26, 'INFORMATICA II', 'I2', true, 1),
    (27, 'PRESUPUESTOS EMPRESARIALES', 'PE', true, 1),
    (28, 'TALLER DE COSTOS', 'TC', true, 1),
    (29, 'ANALISIS E INTERPRETACION DE EE.FF.', 'AI', true, 1),
    (30, 'ORGANIZACION Y METODOS', 'OM', true, 1),
    (31, 'ECONOMIA FISCAL', 'EF', true, 1),
    (32, 'PREPARACION Y EVALUACION DE PROYECTOS', 'PEP', true, 1),
    (33, 'PRESUPUESTOS FISCALES', 'PF', true, 1),
    (34, 'AUDITORIA I', 'AI', true, 1),
    (35, 'ECONOMIA MONETARIA', 'EM', true, 1),
    (36, 'AUDITORIA TRIBUTARIA I', 'ATI', true, 1),
    (37, 'SEMINARIO SUPERIOR', 'SS', true, 1),
    (38, 'AUDITORIA II', 'AII', true, 1),
    (39, 'CONTABILIDAD INTEGRADA', 'CI', true, 1),
    (40, 'AUDITORIA TRIBUTARIA II', 'ATII', true, 1),
    (41, 'METODOS Y TECNICAS DE INVESTIGACION', 'MTI', true, 1),
    (42, 'ADMINISTRACION FINANCIERA', 'AF', true, 1),
    (43, 'GABINETE DE AUDITORIA', 'GA', true, 1),
    (44, 'TALLER DE TITULACION', 'TT', true, 1),
    (45, 'AUDITORIA FORENSE', 'AF', true, 1),
    (46, 'AUDITORIA DE GESTION', 'AG', true, 1),
    (47, 'METODOLOGIA DE INVESTIGACION I', 'MI', true, 1),
    (48, 'INTRODUCCION A LA INGENIERIA COMERCIAL', 'IIC', true, 1),
    (49, 'CONTABILIDAD GERENCIAL', 'CG', true, 1),
    (50, 'ALGEBRA LINEAL', 'AL', true, 1),
    (51, 'CALCULO I', 'CI', true, 1),
    (52, 'TEORIA Y TECNICAS DE LA ORGANIZACION', 'TTO', true, 1),
    (53, 'CONTABILIDAD PARA LA GESTION', 'CPG', true, 1),
    (54, 'CALCULO II', 'CII', true, 1),
    (55, 'ECONOMIA DE EMPRESAS', 'EE', true, 1),
    (56, 'INGLES I', 'II', true, 1),
    (57, 'ESTADISTICA II', 'EII', true, 1),
    (58, 'GESTION DE LA ADMINISTRACION I', 'GAI', true, 1),
    (59, 'COSTOS EMPRESARIALES', 'CE', true, 1),
    (60, 'DERECHO COMERCIAL Y LABORAL', 'DCL', true, 1),
    (61, 'INGLES II', 'II', true, 1),
    (62, 'MACROECONOMIA', 'M', true, 1),
    (63, 'COSTOS PARA LA TOMA DE DECISIONES', 'CTD', true, 1),
    (64, 'ANALISIS DE ESTADOS FINANCIEROS', 'AEF', true, 1),
    (65, 'PROGRAMACION BASICA', 'PB', true, 1),
    (66, 'INVESTIGACION OPERATIVA I', 'IO', true, 1),
    (67, 'PRESUPUESTOS', 'P', true, 1),
    (68, 'GESTION DE LA ADMINISTRACION II', 'GAII', true, 1),
    (69, 'INVESTIGACION OPERATIVA II', 'IIO', true, 1),
    (70, 'SISTEMA DE INFORMACION PARA LA GESTION I', 'SIGI', true, 1),
    (71, 'ECOLOGIA Y MEDIO AMBIENTE', 'EMA', true, 1),
    (72, 'PSICOLOGIA ORGANIZACIONAL', 'PO', true, 1),
    (73, 'PROCESOS INDUSTRIALES (PRODUCCION)', 'PIP', true, 1),
    (74, 'LOGISTICA PARA OPERACIONES', 'LO', true, 1),
    (75, 'FINANZAS', 'F', true, 1),
    (76, 'MERCADOTECNIA', 'M', true, 1),
    (77, 'RECURSOS HUMANOS', 'RH', true, 1),
    (78, 'DIRECCION EMPRESARIAL', 'DE', true, 1),
    (79, 'GESTION FINANCIERA', 'GF', true, 1),
    (80, 'INVESTIGACION DE MERCADOS', 'IM', true, 1),
    (81, 'COMERCIO EXTERIOR', 'CE', true, 1),
    (82, 'MARKETING DE SERVICIOS Y RELACIONAL', 'MSR', true, 1),
    (83, 'ECONOMETRIA Y SIMULACIONES', 'ES', true, 1),
    (84, 'REGIMEN TRIBUTARIO Y ADUANERO', 'RTA', true, 1),
    (85, 'GESTION DE CALIDAD', 'GC', true, 1),
    (86, 'SEGURIDAD E HIGIENE INDUSTRIAL', 'SHI', true, 1);

-- Insertar materias para la Facultad de Ciencias y Tecnología
INSERT INTO subject (id, "name", initials, active, area_id)
VALUES
    (87, 'INGLES I', 'II', true, 2),
    (88, 'FISICA GENERAL', 'FG', true, 2),
    (89, 'ALGEBRA I', 'AI', true, 2),
    (90, 'CALCULO I', 'CI', true, 2),
    (91, 'INTRODUCCION A LA PROGRAMACION', 'IAP', true, 2),
    (92, 'METODOLOGIA INVESTIGACION Y TEC COMUNICACION', 'MITC', true, 2),
    (93, 'ALGEBRA II', 'AII', true, 2),
    (94, 'CALCULO II', 'CII', true, 2),
    (95, 'MATEMATICA DISCRETA', 'MD', true, 2),
    (96, 'ELEM. DE PROGRAMACION Y ESTRUC. DE DATOS', 'EPEED', true, 2),
    (97, 'ARQUITECTURA DE COMPUTADORAS I', 'ACI', true, 2),
    (98, 'ECUACIONES DIFERENCIALES', 'ED', true, 2),
    (99, 'ESTADISTICA I', 'EI', true, 2),
    (100, 'CALCULO NUMERICO', 'CN', true, 2),
    (101, 'BASE DE DATOS I', 'BDI', true, 2),
    (102, 'CIRCUITOS ELECTRONICOS', 'CE', true, 2),
    (103, 'ESTADISTICA II', 'EII', true, 2),
    (104, 'BASE DE DATOS II', 'BDII', true, 2),
    (105, 'TALLER DE SISTEMAS OPERATIVOS', 'TSO', true, 2),
    (106, 'SISTEMAS DE INFORMACION I', 'SII', true, 2),
    (107, 'CONTABILIDAD BASICA', 'CB', true, 2),
    (108, 'INVESTIGACION OPERATIVA I', 'IOI', true, 2),
    (109, 'INGLES II', 'II', true, 2),
    (110, 'SISTEMAS DE INFORMACION II', 'SII', true, 2),
    (111, 'APLICACION DE SISTEMAS OPERATIVOS', 'ASO', true, 2),
    (112, 'TALLER DE BASE DE DATOS', 'TBD', true, 2),
    (113, 'SISTEMAS I', 'SI', true, 2),
    (114, 'INVESTIGACION OPERATIVA II', 'IOII', true, 2),
    (115, 'MERCADOTECNIA', 'M', true, 2),
    (116, 'SIMULACION DE SISTEMAS', 'SS', true, 2),
    (117, 'INGENIERIA DE SOFTWARE', 'IS', true, 2),
    (118, 'INTELIGENCIA ARTIFICIAL', 'IA', true, 2),
    (119, 'REDES DE COMPUTADORAS', 'RC', true, 2),
    (120, 'SISTEMAS II', 'SII', true, 2),
    (121, 'SISTEMAS ECONOMICOS', 'SE', true, 2),
    (122, 'REDES DE NUEVA GENERACION', 'RNG', true, 2),
    (123, 'TALLER DE INGENIERIA DE SOFTWARE', 'TIS', true, 2),
    (124, 'GESTION DE CALIDAD DE SOFTWARE', 'GCS', true, 2),
    (125, 'REDES AVANZADAS DE COMPUTADORAS', 'RAC', true, 2),
    (126, 'DINAMICA DE SISTEMAS', 'DS', true, 2),
    (127, 'APLIC. INTERACTIVAS PARA TELEVISION DIGITAL', 'AITD', true, 2),
    (128, 'CLOUD COMPUTING', 'CC', true, 2),
    (129, 'ELECTROTECNIA INDUSTRIAL', 'EI', true, 2),
    (130, 'PLANIFICACION Y EVALUACION DE PROYECTOS', 'PEP', true, 2),
    (131, 'INGLES III', 'III', true, 2),
    (132, 'EVALUACION Y AUDITORIA DE SISTEMAS', 'EYAS', true, 2),
    (133, 'TALLER DE SIMULACION DE SISTEMAS', 'TSS', true, 2),
    (134, 'METODOL. Y PLANIF. DE PROYECTO DE GRADO', 'MPPG', true, 2),
    (135, 'SEGURIDAD DE SISTEMAS', 'SS', true, 2),
    (136, 'INFORMATICA FORENSE', 'IF', true, 2),
    (137, 'GESTION ESTRATEGICA DE EMPRESAS', 'GEE', true, 2),
    (138, 'PROYECTO FINAL', 'PF', true, 2),
    (139, 'PRACTICA EMPRESARIAL', 'PE', true, 2),
    (140, 'ENTORNOS VIRTUALES DE APRENDIZAJE', 'EVA', true, 2),
    (141, 'SERVICIOS TELEMATICOS', 'ST', true, 2),
    (142, 'RECONOCIMIENTO DE VOZ', 'RV', true, 2),
    (143, 'BUSINESS INTELLIGENCE Y BIG DATA', 'BIBD', true, 2),
    (144, 'CIENCIA DE DATOS Y MACHINE LEARNING', 'CDML', true, 2),
    (145, 'PLANIF. Y CONTROL DE LA PRODUCCION I', 'PCPI', true, 2),
    (146, 'INGENIERIA ECONOMICA', 'IE', true, 2),
    (147, 'PLANIF. Y CONTROL DE LA PRODUCCION II', 'PCPII', true, 2),
    (148, 'COSTOS INDUSTRIALES', 'CI', true, 2),
    (149, 'INGENIERIA DE METODOS Y REINGENIERIA', 'IMR', true, 2),
    (150, 'DISEÑO DE COMPILADORES', 'DC', true, 2);

-- Insertar materias para la Facultad de Humanidades
INSERT INTO subject (id, "name", initials, active, area_id)
VALUES
    (151, 'FUNDAMENTOS DE LA PSICOLOGIA', 'FP', true, 3),
    (152, 'PSICOFISIOLOGIA I', 'PI', true, 3),
    (153, 'FORMACION SOCIAL BOLIVIANA', 'FSB', true, 3),
    (154, 'FUNDAMENTOS FILOSOFICOS DE LA PSICOLOGIA', 'FFP', true, 3),
    (155, 'PSICOESTADISTICA', 'PES', true, 3),
    (156, 'ANALISIS DEL COMPORTAMIENTO I', 'ACI', true, 3),
    (157, 'PSICOFISIOLOGIA II', 'PII', true, 3),
    (158, 'PSICOLOGIA FENOMENOLOGICA I', 'PFI', true, 3),
    (159, 'ANTROPOLOGIA SOCIAL BOLIVIANA', 'ASB', true, 3),
    (160, 'METODOS Y TEC. DE INVESTIGACION CUANTITATIVA', 'MTIC', true, 3),
    (161, 'QUECHUA I', 'QI', true, 3),
    (162, 'FRANCES I', 'FI', true, 3),
    (163, 'INGLES I', 'II', true, 3),
    (164, 'PSICOANALISIS I', 'PI', true, 3),
    (165, 'ANALISIS DEL COMPORTAMIENTO II', 'ACII', true, 3),
    (166, 'PSICOLOGIA FENOMENOLOGICA II', 'PFII', true, 3),
    (167, 'PSICOLOGIA DE LA GESTALT', 'PG', true, 3),
    (168, 'PSICOLOGIA COGNITIVA I', 'PCI', true, 3),
    (169, 'METODOLOGIAS PARA LA ELAB DE PROYECTOS PSICOL', 'MEPP', true, 3),
    (170, 'QUECHUA II', 'QII', true, 3),
    (171, 'FRANCES II', 'FII', true, 3),
    (172, 'INGLES II', 'III', true, 3),
    (173, 'PSICOANALISIS II', 'PII', true, 3),
    (174, 'ETNOPSICOLOGIA', 'E', true, 3),
    (175, 'PSICOLOGIA COGNITIVA II', 'PCII', true, 3),
    (176, 'PSICOLOGIA GENETICA', 'PG', true, 3),
    (177, 'PSICOLOGIA SISTEMICA', 'PS', true, 3),
    (178, 'PSICOLINGUISTICA', 'PL', true, 3),
    (179, 'PSICOLOGIA SOCIAL', 'PS', true, 3),
    (180, 'PSICOLOGIA DE LA COMUNICACION', 'PC', true, 3),
    (181, 'PSICOPATOLOGIA I', 'PI', true, 3),
    (182, 'PSICOMETRIA I', 'PI', true, 3),
    (183, 'TECNICAS PROYECTIVAS I', 'TPI', true, 3),
    (184, 'PSICOPATOLOGIA II', 'PII', true, 3),
    (185, 'PSICOFARMACOLOGIA - ELECTIVA', 'P-E', true, 3),
    (186, 'PSICOLOGIA DEL APRENDIZAJE', 'PA', true, 3),
    (187, 'PSICOLOGIA DE LA SEXUALIDAD - ELECTIVA', 'PSE', true, 3),
    (188, 'ENTREVISTA PSICOLOGICA', 'EP', true, 3),
    (189, 'PSICOMETRIA II', 'PII', true, 3),
    (190, 'PSICOLOGIA INSTITUCIONAL', 'PI', true, 3),
    (191, 'PSICOLOGIA EDUCATIVA I', 'PEI', true, 3),
    (192, 'TECNICAS PROYECTIVAS II', 'TP2', true, 3),
    (193, 'PSICOTERAPIA - ELECTIVA', 'P-E', true, 3),
    (194, 'DINAMICA DE GRUPO I', 'DGI', true, 3),
    (195, 'METODOS Y TEC. DE INVESTIGACION CUALITATIVA', 'MTIC', true, 3),
    (196, 'PSICOLOGIA SOCIAL II - ELECTIVA', 'PS2-E', true, 3),
    (197, 'PSICOLOGIA EDUCATIVA II', 'PEII', true, 3),
    (198, 'PSICODIAGNOSTICO', 'PD', true, 3),
    (199, 'DINAMICA DE GRUPO II', 'DGII', true, 3),
    (200, 'EDUCACION ESPECIAL', 'EE', true, 3),
    (201, 'CLINICA COGNITIVO COMPT.', 'CCC', true, 3),
    (202, 'CLINICA PSICOANALITICA I', 'CPI', true, 3),
    (203, 'CLINICA SISTEMICA', 'CS', true, 3),
    (204, 'INTERCULTURALIDAD Y BILINGÜISMO', 'IYB', true, 3),
    (205, 'PSICOLOGIA AMBIENTAL', 'PA', true, 3),
    (206, 'PSICOLOGIA COMUNITARIA I', 'PCI', true, 3),
    (207, 'PSICOLOGIA ORGANIZACIONAL I', 'POI', true, 3),
    (208, 'PSICOLOGIA PREVENTIVA', 'PP', true, 3),
    (209, 'TECNICAS E INSTR. DE INTERVENCION PSICOSOCIAL', 'TEIIP', true, 3),
    (210, 'SEMINARIO EVALUACION PSICOLOGICA', 'SEP', true, 3),
    (211, 'TECNICAS PROYECTIVAS III', 'TP3', true, 3),
    (212, 'ORIENTACION VOCACIONAL', 'OV', true, 3),
    (213, 'PSICOLOGIA ORGANIZACIONAL II', 'POII', true, 3),
    (214, 'CLINICA PSICOANALITICA II', 'CPII', true, 3),
    (215, 'PSICOLOGIA COMUNITARIA II', 'PCII', true, 3),
    (216, 'PSICOPEDAGOGIA', 'PP', true, 3),
    (217, 'PSICOLOGIA FORENSE - ELECTIVA', 'PF-E', true, 3),
    (218, 'INTERVENCION SOCIAL COMUNITARIA', 'ISC', true, 3),
    (219, 'MODALIDAD DE GRADUACION I', 'MGI', true, 3),
    (220, 'MODALIDAD DE GRADUACION I AREA EDUCATIVA', 'MGIAE', true, 3),
    (221, 'MODALIDAD DE GRADUACION I AREA SOCIAL', 'MGIAS', true, 3),
    (222, 'MODALIDAD DE GRADUACION I AREA CLINICA', 'MGIAC', true, 3),
    (223, 'MODALIDAD DE GRAD. INTERNADO I', 'MGII', true, 3),
    (224, 'MODALIDAD DE GRAD. INTERNADO I (AREA EDUCATI)', 'MGIIE', true, 3),
    (225, 'MODALIDAD DE GRAD. INTERNADO I (AREA SOCIAL)', 'MGIIS', true, 3),
    (226, 'MODALIDAD DE GRAD. INTERNADO I (AREA CLINICA)', 'MGIIC', true, 3),
    (227, 'PRACTICA INSTITUCIONAL', 'PI', true, 3),
    (228, 'TITULACION', 'T', true, 3),
    (229, 'PRACTICA INSTITUCIONAL AREA EDUCATIVA', 'PIAE', true, 3),
    (230, 'PRACTICA INSTITUCIONAL AREA SOCIAL', 'PIAS', true, 3),
    (231, 'PRACTICA INSTITUCIONAL AREA CLINICA', 'PIAC', true, 3),
    (232, 'MODALIDAD DE GRADUACION II', 'MGII', true, 3),
    (233, 'MODALIDAD DE GRADUACION II AREA EDUCATIVA', 'MGIIE', true, 3),
    (234, 'MODALIDAD DE GRADUACION II AREA SOCIAL', 'MGIIS', true, 3),
    (235, 'MODALIDAD DE GRADUACION II AREA CLINICA', 'MGIIC', true, 3),
    (236, 'MODALIDAD DE GRADUACION INTERNADO II', 'MGIII', true, 3),
    (237, 'MODALIDAD DE GRAD. INTERNADO II (AREA EDUCAT)', 'MGIIIE', true, 3),
    (238, 'MODALIDAD DE GRAD. INTERNADO II (AREA SOCIAL)', 'MGIIIS', true, 3),
    (239, 'MODALIDAD DE GRAD INTERNADO II (AREA CLINICA)', 'MGIIIC', true, 3);

SELECT setval('subject_sequence', 239, true); --next value will be 240
