server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.15:5433/am_db_test
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://root:password@192.168.0.15:27018/candidate
      port: 27018
      database: candidate
      username: root
      password: password
  flyway:
    locations: classpath:db/migration,classpath:qa/db/migration
