server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.15:5435/am_db_dev
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://root:password@192.168.0.15:27022/candidate
      port: 27017
      database: candidate
      username: root
      password: password
  flyway:
    locations: classpath:db/migration,classpath:dev/db/migration
